---
#- debug:
#    msg: "{{ vars }}"
#    #var: ansible_user_id
#  when: DEBUG | d() | bool

- debug:
    var: environment
  when: DEBUG | d() | bool

- debug:
    var: hostvars
  when: DEBUG | d() | bool

- include_tasks: configure.yml
